### PR TITLE
OWXP-135 Add markdown format to wiki

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/OWXP-135

Added a resource bundle module owxp-lang to be able to localize the format name. Other ways didn't work. From now any other modules can use it to store language keys if it's ok.

Br,
Norbert

### CODE REVIEW

**Comment by moltam89** [comment]
Hi Norbi,

I got a BundleException when I tried to deploy the new module:
`org.osgi.framework.BundleException: Could not resolve module: wiki.engine.markdown [520]_  Unresolved requirement: Import-Package: net.htmlparser.jericho_`

Do I need something special to deploy it?

Thanks,
Tamás

**Comment by NorbertKocsis** [comment]
Hi,

Interesting... It should be included in the bundle and my build doesn't even list it as an Import-Package. Nothing special should be needed to deploy.

Br,
Norbert

**Comment by moltam89** [comment]
I just realized that I already got some warnings when I ran the deploy task:

`[Can not find JAR file 'asm-[0-9]*.jar', Can not find JAR file 'asm-analysis-[0-9]*.jar', Can not find JAR file 'asm-tree-[0-9]*.jar', Can not find JAR file 'asm-util-[0-9]*.jar', Can not find JAR file 'jericho-html-[0-9]*.jar', Can not find JAR file 'parboiled-core-[0-9]*.jar', Can not find JAR file 'parboiled-java-[0-9]*.jar', Can not find JAR file 'pegdown-[0-9]*.jar']`

Any ideas?

**Comment by NorbertKocsis** [comment]
gw dependencies or in Lideray IDE: Gradle > Refresh Gradle project might help. Seems like the dependencies are not downloaded.

**Comment by moltam89** [comment]
I tried that one already, didn't help :/

**Comment by NorbertKocsis** [comment]
Weird... I have nothing special set in my workspace.

**Comment by moltam89** [comment]
Hi @hudakl,

could you please help out here?

I'd like you to try and deploy Norbi's new module, to see if it's working for you.

If it will work for you as well, then I'll know that the problem is at my side.

Thanks,
Tamás

**Comment by hudakl** [comment]
Hi,

It got deployed for me successfully. The jars, for which you got the warning messages, were downloaded upon deployin. Perhaps, something is wrong with your configuration regarding the nexus repository.
I don't know where are the settings for that, though.

Laci

**Comment by moltam89** [comment]
Hi guys,

@hudakl , thanks for the help!

The jars are downloaded at my side as well, but to the gradle chache:
c:\Users\tamas.molnar\.gradle\caches\modules-2\files-2.1\...

Is it something similar for you?

I can't see how the **-includeresource** from bnd.bnd should find those jars.

For now I, I copied the jars to a temp folder and changed the bnd.bnd to cotnain the path as well, so I got something like this:
**-includeresource:\\**
	**asm-5.0.3.jar=c:/Users/tamas.molnar/Downloads/dependencies/asm-5.0.3.jar,\\**

Now the jars are included, but I still got the same error:

> org.osgi.framework.BundleException: Could not resolve module: wiki.engine.markdown [596]_  Unresolved requirement: Import-Package: net.htmlparser.jericho_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:429)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)
                        22:32:20,587 INFO  [Thread-135][LCSClusterEntryTokenAdvisor:238] Unable to find the LCS cluster entry token file

Could you please attach your jar file?
Here is mine, my plan is to compare them, to see what is the difference.

[wiki.engine.markdown-1.0.0.jar.zip](https://github.com/moltam89/OWXP/files/812217/wiki.engine.markdown-1.0.0.jar.zip)

Thanks,
Tamás

**Comment by NorbertKocsis** [comment]
Here's my jar:
[wiki.engine.markdown-1.0.0.jar.zip](https://github.com/moltam89/OWXP/files/813371/wiki.engine.markdown-1.0.0.jar.zip)

**Comment by NorbertKocsis** [comment]
Interesting. Your jar contains the jar files instead of just containing the classes.

The jars are in the gradle cache on my side also.

**Comment by moltam89** [comment]
I succeeded finally!

I realized that the bnd version is different in the manifest files (mine was lower).

I already had the latest BLADE version, but once I created a new Liferay workspace everything started working smoothly. 

It's still pretty weird, but at least it's working at my side as well.
I'll review it as soon as I can.

Thanks for the help!

**Comment by moltam89** [comment]
Forwarded to https://github.com/holatuwol/OWXP/pull/1.

Thanks,
Tamás

**Pull request closed without merging**
