### PR TITLE
[GROW-117, GROW-153]

### PR DESCRIPTION
**Pull request by istvansajtos**
[GROW-117](https://issues.liferay.com/browse/GROW-117)
[GROW-351](https://issues.liferay.com/browse/GROW-351)

Hi Tomcsi,

This is the continuation of https://github.com/moltam89/OWXP/pull/18 + contains 
- requested improvements and
- Ugur's changes for GROW-351

When reviewing, you can jump immediately to the commit *"GROW-117 Fix incorrect activity ordering"* because I left my original commits intact.

Thanks for reviewing this,
Pisti

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @istvansajtos , @ugurcancetin ,

I got a NullPointerException when I tried to deploy the new modules, furthermore the formatSource task fails.

Could you please take a look at?

Thanks,
Tamás 
> 13:40:56,265 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.api_1.0.0 [663]
13:40:56,296 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.interpreter_1.0.0 [664]
13:41:01,393 INFO  [Refresh Thread: Equinox Container: 80b08c7a-5eb2-0017-1985-e237cfbf2674][BundleStartStopLogger:38] STOPPED com.liferay.social.activities.web_1.1.5 [126]
13:41:01,880 INFO  [Refresh Thread: Equinox Container: 80b08c7a-5eb2-0017-1985-e237cfbf2674][BundleStartStopLogger:35] STARTED com.liferay.social.activities.web_1.1.5 [126]
13:41:01,890 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.core.language.keys_1.0.0 [666]
13:41:01,902 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.core.jsp_1.0.0 [665]
13:41:01,910 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.service.wrapper_1.0.0 [669]
13:41:01,912 INFO  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.social.activity.customizer.service_1.0.0 [668]
13:41:02,137 ERROR [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][ModuleApplicationContextRegistrator:80] Unable to start com.liferay.social.activity.customizer.service
com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
        at com.liferay.portal.service.impl.ServiceComponentLocalServiceImpl.initServiceComponent(ServiceComponentLocalServiceImpl.java:245)
        at sun.reflect.GeneratedMethodAccessor348.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:163)
        at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:46)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:39)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.cache.thread.local.ThreadLocalCacheAdvice.invoke(ThreadLocalCacheAdvice.java:48)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:169)
        at com.sun.proxy.$Proxy241.initServiceComponent(Unknown Source)
        at com.liferay.portal.service.configuration.configurator.impl.ServiceConfiguratorImpl.initServiceComponent(ServiceConfiguratorImpl.java:156)
        at com.liferay.portal.service.configuration.configurator.impl.ServiceConfiguratorImpl.initServices(ServiceConfiguratorImpl.java:69)
        at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:66)
        at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.felix.dm.InvocationUtil.invokeMethod(InvocationUtil.java:111)
        at org.apache.felix.dm.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:66)
        at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:769)
        at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:760)
        at org.apache.felix.dm.impl.ComponentImpl.bindService(ComponentImpl.java:705)
        at org.apache.felix.dm.impl.ComponentImpl.access$400(ComponentImpl.java:54)
        at org.apache.felix.dm.impl.ComponentImpl$7.run(ComponentImpl.java:202)
        at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:137)
        at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:119)
        at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:85)
        at org.apache.felix.dm.impl.ComponentImpl.calculateStateChanges(ComponentImpl.java:252)
        at org.apache.felix.dm.impl.ComponentImpl.start(ComponentImpl.java:440)
        at org.apache.felix.dm.DependencyManager.add(DependencyManager.java:167)
        at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender$ModuleApplicationContextExtension.start(ModuleApplicationContextExtender.java:391)
        at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)
        at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:905)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:461)
        at org.eclipse.osgi.container.Module.start(Module.java:452)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at com.liferay.portal.kernel.util.StringUtil.read(StringUtil.java:2320)
        at com.liferay.portal.service.impl.ServiceComponentLocalServiceImpl.initServiceComponent(ServiceComponentLocalServiceImpl.java:184)
        ... 72 more
13:41:02,139 WARN  [fileinstall-C:/liferay/bundles/liferay-7.0.x-ee/DXP/osgi/modules][com_liferay_social_activity_customizer_service:103] Invocation of 'start' failed.
com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
        at com.liferay.portal.service.impl.ServiceComponentLocalServiceImpl.initServiceComponent(ServiceComponentLocalServiceImpl.java:245)
        at sun.reflect.GeneratedMethodAccessor348.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:163)
        at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:46)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:39)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.cache.thread.local.ThreadLocalCacheAdvice.invoke(ThreadLocalCacheAdvice.java:48)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
        at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
        at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:169)
        at com.sun.proxy.$Proxy241.initServiceComponent(Unknown Source)
        at com.liferay.portal.service.configuration.configurator.impl.ServiceConfiguratorImpl.initServiceComponent(ServiceConfiguratorImpl.java:156)
        at com.liferay.portal.service.configuration.configurator.impl.ServiceConfiguratorImpl.initServices(ServiceConfiguratorImpl.java:69)
        at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:66)
        at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.felix.dm.InvocationUtil.invokeMethod(InvocationUtil.java:111)
        at org.apache.felix.dm.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:66)
        at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:769)
        at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:760)
        at org.apache.felix.dm.impl.ComponentImpl.bindService(ComponentImpl.java:705)
        at org.apache.felix.dm.impl.ComponentImpl.access$400(ComponentImpl.java:54)
        at org.apache.felix.dm.impl.ComponentImpl$7.run(ComponentImpl.java:202)
        at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:137)
        at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:119)
        at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:85)
        at org.apache.felix.dm.impl.ComponentImpl.calculateStateChanges(ComponentImpl.java:252)
        at org.apache.felix.dm.impl.ComponentImpl.start(ComponentImpl.java:440)
        at org.apache.felix.dm.DependencyManager.add(DependencyManager.java:167)
        at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender$ModuleApplicationContextExtension.start(ModuleApplicationContextExtender.java:391)
        at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)
        at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:905)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:461)
        at org.eclipse.osgi.container.Module.start(Module.java:452)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at com.liferay.portal.kernel.util.StringUtil.read(StringUtil.java:2320)
        at com.liferay.portal.service.impl.ServiceComponentLocalServiceImpl.initServiceComponent(ServiceComponentLocalServiceImpl.java:184)
        ... 72 more

**Comment by istvansajtos** [comment]
Hi @moltam89,

The deployment issue is 
- reproducible with with de-29 + hotfix-1239 (at least in a vanilla environment)
- NOT reproducible with de-12 + hotfix-976

I will update you once I have more info.

Regards,

**Comment by istvansajtos** [comment]
Hi  @moltam89 ,

I've updated the PR with two commits:

**GROW-351 SF**
Adds missing SF, but doesn't solve the failure of formatSource Gradle task. It occurs because Gradle uses an outdated com.liferay.source.formatter.jar. Do you know how to overcome this?

**GROW-117 Partial revert of 41b826a - NullPointerException occurs due to ModuleResourceLoader changes (LPS-73967) in new fix-pack**
Solves the deployment failure.

Thanks,
Pisti

**Comment by moltam89** [comment]
@ugurcancetin 
It seems to me that your changes break the attachment related activities,  could you please take a look at?

Thanks,
Tamás

**Comment by ugurcancetin** [comment]
@moltam89 good catch eagle eyes :+1: :) Will be updated soon.

**Comment by istvansajtos** [comment]
Hi @moltam89 ,

I've updated the PR with @ugurcancetin's suggested changes.

Thanks,

**Comment by moltam89** [comment]
Hi @istvansajtos , @ugurcancetin ,

**about the formaSource task:**

I could only do a nasty workaround to run it successfully.
As Pisti described it, for some reason an outdated **com.liferay.source.formatter.jar** is used and I couldn't figure it out how to change it.

Therefore I replaced the jar file manually. For me the com.liferay.source.formatter-1.0.439.jar is used which is under

c:\Users\tamas.molnar\.gradle\caches\modules-2\files-2.1\com.liferay\com.liferay.source.formatter\1.0.439\2bd251a8e981dc22f19ecf4da1ead4b5bbed5fb8\

I downloaded the latest version of this module (
[com.liferay.source.formatter-1.0.484.jar.zip](https://github.com/moltam89/OWXP/files/1415209/com.liferay.source.formatter-1.0.484.jar.zip)), renamed it to com.liferay.source.formatter-1.0.439.jar and replaced the original jar.

Could you please do something similar? Let me know if you need help.

There are several warnings when I run the formaSource task and I would like to ask you guys to fix them.

Thanks,
Tamás

**Comment by istvansajtos** [comment]
Hi @moltam89 ,

This formatSource misery seems to be ending finally. Let me share what I have found:

The version of *com.liferay.source.formatter* is indirectly controlled by *com.liferay.gradle.plugins.workspace*. You can increase its version to 1.7.0 in *settings.gradle* (not version-controlled) BUT it won't solve the [NPE mentioned here](https://github.com/moltam89/OWXP/pull/20#issuecomment-336890527). NPE won't occur once [LPS-72705](https://github.com/liferay/liferay-portal-ee/commit/d0dd7ff529327f6c04c5babd555ea6d8cdaccd71#diff-15fb8ecd2cc5c5704aed43c0788db73a) is included in the source formatter jar, for the time being I detected the formatting problem myself. 

As you draw my attention, the more up-to-date com.liferay.source.formatter.jar indicated several warnings, so I eliminated those too. The new **GROW-117 SF** commit contains all these changes.

**PS:** I don't suggest the mentioned version update, becasuse it may cause you serious source formatting headache with other modules too.

Thank you,
Pisti

**Comment by moltam89** [comment]
Hi @istvansajtos ,

sorry for the slow review, I was quite busy nowadays.

About the source formatting, I still get 2 warnings when I run the formatSource task, can we get rid of these?

`Package should follow Bundle-SymbolicName specified in ./bnd.bnd, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/package.markdown: ./src/main/java/com/liferay/social/activity/customizer/interpreter/GeneralWikiActivityInterpreter.java
Package should follow Bundle-SymbolicName specified in ./bnd.bnd, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/package.markdown: ./src/main/java/com/liferay/social/activity/customizer/interpreter/CustomWikiActivityInterpreter.java`

Thanks,
Tamás

**Comment by istvansajtos** [comment]
Thanks @moltam89 ! I will look into it today.

**Comment by istvansajtos** [comment]
Hi @moltam89 ,

There are no warning on my machine. The commit [GROW-117 SF](https://github.com/moltam89/OWXP/pull/20/commits/ce40a0892688964b31bb5459da36b100ba534510) should handle these cases too. 

Let me know when you have time to double-check together on your machine.

Thanks!

**Comment by istvansajtos** [comment]
Hi @moltam89,

Please see additional commits for fixing

- pagination issue
- HTML/CSS formatting problems

Please note, the formatting was aligned to what we see in search results (Search portlet), because we display almost the same data (title, excerpt, tags + some extra info). Therefore I choose to reuse HTML/CSS from main_search.jspf (and docroot/html/taglib/ui/asset_tags_summary/page.jsp for tag formatting).

None of them is tested with real world data yet, but looked good at first glance. :)

I hope the guys can start testing the new theme on profile page with these.

Regards,

**Comment by moltam89** [comment]
https://github.com/istvansajtos/OWXP/pull/2

**Pull request closed without merging**
